[tool.poetry]
name = "starbuzz"
version = "0.1.0"
description = "Star Buzz"
authors = ["Marco André Mendes <marcoandre@gmail.com>"]
license = "GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
